### PR TITLE
Link fixes

### PR DESCRIPTION
**Pull request by yatil**
That should fix https://github.com/w3c/wai-translations/issues/42 is I understood correctly. If I did not, I just wasted two hours ;-) 

>  EE: for links within the content, the system adds "(in English)"[in language] next to page titles (per Language of links/resource titles within the content & Language of links to other pages)

That functionality was already there…

>  SLH or EE: fix added links in Video Intro pages (in English version and all the updated translations)

This PR does that.

> SLH or EE: delete redundant (in English) in Russian -- and French after we get the update

I did not find any redundant (in English).

### CODE REVIEW

**Comment by yatil** [comment]
Yeah, it is pretty buggy and not tested. The text in Fallback should be in the language of the document, I think. Then, when a translation of the target document is available, the fallback text is replaced by the actual title of the document.

**Comment by slhenry** [comment]
ah, right! now I remember!

I'll write up some notes and make some tweaks and get back to this PR in a bit.

**Comment by slhenry** [comment]
> Then, when a translation of the target document is available, the fallback text is replaced by the actual title of the document.

This is great for the future, yet low priority for now, esp since we have so few other translations.

**Comment by yatil** [comment]
> > Then, when a translation of the target document is available, the fallback text is replaced by the actual title of the document.
> This is great for the future, yet low priority for now, esp since we have so few other translations.

Well, that’s the part where I’m sure it's working :-D

**Comment by slhenry** [comment]
I documented it [here ](https://www.w3.org/wiki/WAI_Translations#Prep_Page_for_Translation)so I know when I forget again. ;-)

**Comment by slhenry** [comment]
Hi Eric. I think:
* all needed text is translated.
* we need to change some "text=" to "fallback=" for page titles. However, it's fine as is for MVP. I propose we update the related issue and leave it open, but not take the time to fix that now.

What do you think?

**Comment by yatil** [comment]
> we need to change some "text=" to "fallback=" for page titles. However, it's fine as is for MVP. I propose we update the related issue and leave it open, but not take the time to fix that now.

Yeah, that’s ok for now. The fallback stuff was broken, so I used text. (It might even be overkill at the moment :-D)

**Comment by yatil** [comment]
So, can we merge this?

**Comment by yatil** [comment]
Oh, I haven’t seen the approval. :-D This is quite a PR! Good job! Merging now!

**Pull request merged**
