### PR TITLE
[el] Greek updates (QA requested from translator)

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by yatil** [comment]
Any specific reason you want to wait with QA until it is merged instead of using the deploy preview link above? (I just want to know the needs here :-))

https://deploy-preview-40--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/el

**Comment by slhenry** [comment]
"(in English)" showing up without my realizing it made me thing things were not in synch. looks good now!

**Comment by yatil** [comment]
This (and #37) are conflicting (because of the fix links PR overlapping. I merge the PRs locally and close these PRs so we can iterate on non-conflicted copies.

**Comment by slhenry** [comment]
/me was worried about that. Have on our 1:1 to figure out better way to avoid that if possible.

**Comment by yatil** [comment]
> /me was worried about that. Have on our 1:1 to figure out better way to avoid that if possible.

Actually, that is exactly what should happen, we both edited the same files at the same time, that rarely happens. And if it does, that’s why this system exists ;-)

**Pull request merged**
