### PR TITLE
[FR] translation for index, complete

### PR DESCRIPTION
**Pull request by notabene**
This would need a proofreading, I'll ask @Sylvie42 directly once the Pull request is merged.

### CODE REVIEW

**Comment by yatil** [comment]
@notabene Can you adopt the changes @slhenry did a few hours ago? https://github.com/w3c/wai-video-standards-and-benefits/commit/f39d6209373d474e0b105445986643b56b68c412 Thanks.

**Comment by yatil** [comment]
related: https://github.com/w3c/wai-video-standards-and-benefits/issues/12, so the formatting can change

**Comment by notabene** [comment]
> @notabene Can you adopt the changes @slhenry did a few hours ago? [f39d620](https://github.com/w3c/wai-video-standards-and-benefits/commit/f39d6209373d474e0b105445986643b56b68c412) Thanks.

Sure I can, adding it to my TO-DO list for when I come back from holidays (3rd of January).
Until then, happy holidays @yatil @slhenry :champagne:

**Comment by slhenry** [comment]
@notabene - no changes needed. They were already done in the file that you translated. :-)

**Comment by notabene** [comment]
@slhenry OK, thanks!

**Pull request merged**
