### PR TITLE
Add ko translation

### PR DESCRIPTION
**Pull request by yonguilee**
I did Korean translation. Please check.
I used the vtt.ko file's content in this file's transcript table like what Shawn said to me :)

Sorry for confusing the language short code. I changed the file name 'index.kr.md' to 'index.ko.md' but not commit message.

### CODE REVIEW

**Comment by slhenry** [comment]
Hi YongUi Lee. Thank you!

The preview is at:
https://deploy-preview-57--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/ko

Please translate "Translating WAI Resources" in the last sentence.

In the preview, the things that say "needs translation" should be updated soon, when @yatil gets to it. :-)

**Comment by yonguilee** [comment]
Hi @slhenry. I translated the "Translating WAI Resources" and also changed some words more appropriate one. (also thanks for correcting my mistake!)

Just freely ask me when "needs translation" part is ready. Thanks :D

**Comment by yatil** [comment]
So… Are we ready to ship this translation? 🛳️

https://deploy-preview-57--keen-mahavira-304f83.netlify.com/videos/standards-and-benefits/ko

**Comment by yonguilee** [comment]
@yatil, I request my colleague to review my translation and I'm on waiting it. 
I'll leave comment when reviewing is done! 

Thanks :)

**Comment by yatil** [comment]
@yonguilee Perfect!

**Comment by yonguilee** [comment]
@slhenry  @yatil, I reflected reviewer's opinion! Review is done. I think now it can be published!

Reviewer info) Jun Ho Lee (gomjunho@gmail.com)

**Comment by slhenry** [comment]
Completed announcement: https://lists.w3.org/Archives/Public/public-wai-translations/2019Jun/0002.html

I approve this for publishing.

@yatil - please publish at your convenience.

**Comment by slhenry** [comment]
ping @yatil :-)

**Comment by yatil** [comment]
@slhenry didn’t have the convenience yet.

**Comment by yatil** [comment]
@yonguilee @slhenry It is now published.

https://www.w3.org/WAI/videos/standards-and-benefits/ko

**Comment by slhenry** [comment]
@yonguilee , To celebrate your translations, I am drinking this tea :-)
KO-tea

**Comment by yonguilee** [comment]
@slhenry , Hooray!😆😆 Do you like green tea? That's one of the most consumed!! I like it too :-)

**Pull request merged**
