### PR TITLE
[Ready to Review] Bahasa Indonesia - Update translation to meet the new able player translation

### LINKED ISSUE #131: Bahasa Indonesia - Video Introduction to Web Accessibility and W3C Standards
I have just updated the Bahasa Indonesia translation for Able Player to better reflect the context and improve its clarity. The changes will impact the document which uses the term "Captions" which was translated as "Teks" to "Takarir" of the Player ([PR can be tracked here](https://github.com/ableplayer/ableplayer/pull/588))

This issue is created in intention of keeping track once the PR in is merged by the Able Player's maintainer.

---

I would like to update the Bahasa Indonesia translation of  the following resource:
- Page URL: https://www.w3.org/WAI/videos/standards-and-benefits/

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

### PR DESCRIPTION
**Pull request by frirasyidi**
This changes is practically the same as this PR: https://github.com/w3c/wai-video-standards-and-benefits/pull/83 except for the Able Player interface call-out which changes the translation of "Caption" from "Teks" to "Takarir".

This translation should be merged after https://github.com/w3c/wai-video-standards-and-benefits/pull/83 and once the Able Player new Bahasa Indonesia translation update PR is merged by its maintainer---which can be monitored here: https://github.com/ableplayer/ableplayer/pull/588. 

cc: @remibetin

### CODE REVIEW

**Comment by remibetin** [comment]
This PR has been split into two:
– Resource update: https://github.com/w3c/wai-video-standards-and-benefits/pull/123
– VTT update: https://github.com/w3c/wai-website-data/pull/114

See https://github.com/w3c/wai-translations/issues/131#issuecomment-1838738576

**Comment by remibetin** [comment]
@frirasyidi I anticipate it will take some time before AblePlayer is updated.

In the meantime, we are in the process of moving many resources to the [`wai-website`](https://github.com/w3c/wai-website) repository, including this one.

I suggest that we close this PR and you open a new one in `wai-website` repository after the AblePlayer update. Is this ok with you?

**Comment by frirasyidi** [comment]
> @frirasyidi I anticipate it will take some time before AblePlayer is updated.
> 
> In the meantime, we are in the process of moving many resources to the [`wai-website`](https://github.com/w3c/wai-website) repository, including this one.
> 
> I suggest that we close this PR and you open a new one in `wai-website` repository after the AblePlayer update. Is this ok with you?

Sorry for the delayed response @remibetin. Yes, that is totally fine with me. Please do let me know once you've finished with the migration so that I can make the MR. Thanks!

**Comment by remibetin** [comment]
Thank you @frirasyidi!

The migration is complete: the content of this resource is now hosted in the following folder https://github.com/w3c/wai-website/tree/master/pages/fundamentals/introduction/video-introduction

**Pull request closed without merging**
